### ISSUE TITLE
Conda installation problems

### ISSUE THREAD

**Issue by SimulationScienceHub** [mcs07/PubChemPy#35]
Hey there,

I tried to download your framework using "conda install -c mcs07 pubchempy" as suggested by the documentation. It's downloaded into the right folder (I can see all the other packages I've ever downloaded there as well), but when I try and install the package in my Anaconda Environment pubchempy is nowhere to be found. 

Any ideas on how to fix this?

Thanks in advance.

**Comment by khoivan88** [comment]
@SimulationScienceHub : I am not an expert in conda but I believe that when you run `conda install -c mcs07 pubchempy`, it already installs pubchempy into your current environment, you don't have to install the package any more. You can test it by going into python IDLE and type `import pubchempy as pcp` and see if it gives any error. If not then you can use it just fine!

**Comment by mcs07** [comment]
If this is still an issue, please share the following details and it will be easier to figure out what the problem is:

- What is the output of `conda info`
- What is the output of `conda list`
- In python, what is the output of `import sys` then `print(sys.path)`
- What are the exact commands you run to install PubChemPy and then use it?
