### ISSUE TITLE
How to get the chemical_vendors

### ISSUE THREAD

**Issue by songpeng** [mcs07/PubChemPy#9]
Hi, 
your package helps me a lot~ 
Now I have a request that given a CID, return its chemical_vendors. The chemical_vendors information is like below : 
![image](https://cloud.githubusercontent.com/assets/6449478/11524735/38351464-9908-11e5-8d23-3b6ed150bdf3.png)
I cannot find such a function in your package, is there a possible way to do that?
Thanks ~
Songpeng

**Comment by songpeng** [comment]
BTW, I see you supplied  the *request* function.
While from PubChem, I cannot find a suitable key word for chemical vendors.

**Comment by mcs07** [comment]
I can't find any mention of vendors on the documentation:
https://pubchem.ncbi.nlm.nih.gov/pug_rest/PUG_REST.html

However, if you watch the network traffic while PubChem assembles a compound page, you can see it uses this endpoint:
https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/categories/compound/2248/JSON

This look like it has the info you want. I have no plans to add this to PubChemPy because it's not part of the official API, but using `urllib2` or `requests` you can retrieve this yourself and parse the response.

**Comment by songpeng** [comment]
Thanks for your information~
Songpeng
